### ISSUE TITLE
Burned NFT still accessible/counted in the api

### ISSUE THREAD

**Issue by Keouf** [ElrondNetwork/api.elrond.com#406]
Hi,

It seems like burned NFT are still counted in the /nfts/count api.
I created a collection of 500 then burned 5 and re minted 5 and the api return a total supply of 505 wich is "false" since I burned 5 of them using the built-in burn function.

**Comment by tanghel** [comment]
Hello! Can you give me the collection details and the burn transactions so we can test this?

Thank you! 🙏

**Comment by Keouf** [comment]
Hi, let's take the collection "MONKSUP-421abc" on the mainnet.
There is a total of 524 NFT returned from the nfts/count API. But some of them are burned.
Here is some tx that show the burns :
- e3d945f6ef4c10c8867b7310277e131998fed448e25a2541325c0aeefcbb7e31
- 9b222ab379b20da551c490be0471ee2de224d7517d31c04f7de357e300e3b7bb
- e2380d19f6033d3e349ad62601cfe597717c15041eb1d782c881d70b635cf7ec
- 384d0a637fa47ae47368df3560991f6a7919480c50c0c44b2a2f644074c1a097

The real count without those burned NFT should be 500.
The only way to see a NFT has been burn right now looks like to be in /nfts/{identifier} where the supply goes to 0, but I think it should be more obvious since those NFT are *gone* forever. Maybe they should'nt show at all in this API ?

Thanks in advance for adressing this !

**Comment by wellbranding** [comment]
I would also encourage to remove burned NFTs from the collection. Minting issues could occur because of the script issues and https://elrondindex.io/rarities  displays broken rarity and dublicates now... It will help tons of projects :)

**Comment by AlexandruPislariu** [comment]
Hello! Can you please give me the identifier of one NFT that should be burnt?
Thank you!

**Comment by tanghel** [comment]
This issue is now being addressed with an update for the elastic indexer, coming soon as well.

For tokens of type `NonFungibleESDT`, once it is burned, it will also be removed and not be returned in the list.

This is the PR with the pending fix: https://github.com/ElrondNetwork/elastic-indexer-go/pull/105

We also have a concept for doing the same for SFTs/MetaESDTs, where this is more tricky, since you may have multiple burn events until a token is completely burned.
