### ISSUE TITLE
Transferring ownership of NFT collection doesn't update cache in API to new owner

### ISSUE THREAD

**Issue by Aerovek-Aviation** [ElrondNetwork/api.elrond.com#421]
When we transfer ownership after creating a NFT collection the API still shows the old ownership address, It takes a couple days to update to the new owner so it makes using the API to get collection by owner not work. Im guessing its just a cache issue.

**Comment by AlexandruPislariu** [comment]
Hello!
Thank you for reporting this issue. You are right, it was just a cache issue.
Now, every transferOwnership transaction will trigger a cache refresh for that specific collection.

I will close this issue since it is solved within this [PR](https://github.com/ElrondNetwork/api.elrond.com/pull/445)
