### ISSUE TITLE
Split Data vs API

### ISSUE THREAD

**Issue by TheoSabattie** [ElrondNetwork/api.elrond.com#451]
Hello! :)

The type definitions (types in "entities" folders (nft, account, etc...)) are usefull when we make request to the api.
It must be separated to another repository/npm so we can use type without importing the whole api.elrond.com framework.

ex:
```ts
import { Account } from "@elrondnetwork/api-types"

const accounts:Account[] = await axios.get("https://api.elrond.com/accounts").data;
```

Thanks in advance! ;)

Théo

**Comment by tanghel** [comment]
Hello!

Thank you for reporting this. We have already discussed this internally. At the moment we don't go along this route because:
- it contains nestjs-specific decorators for swaggerdoc, meaning you would also need to load the nestjs framework, which is probably something you don't want since you're building a client app.
- it complicates our deployment system. We sometimes deploy separate branches on devnet, testnet, staging & mainnet. Maintaining different deployment with different branches would be hell for us if we extract types in a npm package or another repository
- you can find open-source schema generators from swaggerdoc, if there is a need for automation

happy coding! 🔥
