### ISSUE TITLE
api does not return all nft owners

### ISSUE THREAD

**Issue by icegriffinguru** [ElrondNetwork/api.elrond.com#523]
I checked this nft collection has more than 350 nfts on elrond explorer.
However, api only returned 250 nft owners (sum of nfts is smaller than 250).
https://api.elrond.com/nfts/FELCCCTEAM-be19dc/owners?from=300&size=100

I checked another nft collections and the result was the same.

**Comment by CatalinFaurPaul** [comment]
Hi, if we make request to https://api.elrond.com/nfts/count?collection=/FELCCCTEAM-be19dc we can see that this collection count is 250 and we can't request with from=300&size100 because if we do that, that means collection FELCCCTEAM-be19dc count is 400 which is not correct. 

This is another example: we have collection SHAWN-1bc127 with nfts count = 11.
- https://api.elrond.com/nfts/SHAWN-1bc127/owners?from=0&size=11 -> this will return all 11 owners
- https://api.elrond.com/nfts/SHAWN-1bc127/owners?from=11&size=1 -> this will return nothing because this collection doesn't have 12 nfts (count=12) and the twelfth nft does not exist.

I hope that's the answer you're looking for,
Best regards
