### ISSUE TITLE
/nfts/{identifier}/accounts - wrong identifier expected

### ISSUE THREAD

**Issue by dan-merlea** [ElrondNetwork/api.elrond.com#554]
https://api.elrond.com/nfts/KROGAN-54c361-01/accounts -> ok
https://api.elrond.com/nfts/KROGAN-54c361/accounts -> 404

I don't think this request should expect the nonce on identifier. By doing this you limit the response to only 1 nft in which case the pagination doesn't make any sense.

**Comment by aoctavian** [comment]
The /nfts/{identifier}/owners was working with NFTs and SFTs.
Now both /owners and /accounts are working only with SFTs.
Are you going to implement NFTs back or we need to find a solution for this by ourselves?

**Comment by tanghel** [comment]
please try the following:

https://api.elrond.com/nfts/KROGAN-54c361 --- 404 not found
https://api.elrond.com/nfts/KROGAN-54c361-01 --- 200 success

https://api.elrond.com/nfts/KROGAN-54c361/accounts --- 404 not found
https://api.elrond.com/nfts/KROGAN-54c361-01/accounts --- 200 success

It is not normal in a RESTful API to return data for a parent resource that returns 404.

The previous endpoint worked by coincidence, and we removed it since it made no sense to work like that.

You have alternative endpoints, such as `/collections/KROGAN-54c361/nfts?withOwners=true` or you can build your own endpoints.

**Comment by dan-merlea** [comment]
That's really bad !! I only need the owners, not the entire object. 
This decision will definitely result in more spam on the API. Getting all owners will take ~ 100 requests instead of 7-10.
