### ISSUE TITLE
Missing documentation for the smart contract querying change

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#661]
Hey!

Up until shortly, I was able to use `/vm-values/int` and `/vm-values/string` to query smart contract data.

I believe you replaced these 2 endpoints with `/query`, however I can't figure out how to use it without `500 Internal Server Error`...

The swagger docs explain nothing about how to use the endpoint.

Could you shed a light on an example usage?

Here's one of my old requests that doesn't work anymore now:
```
POST https://devnet-api.elrond.com/vm-values/int
Body:
{
	"scAddress": "erd1qqqqqqqqqqqqqpgq9n3hue8hkpjtd4w74jjlctgxltkuarj9jz0sak8w36",
	"funcName": "getNftPrice"
}
```
Response:
```
{
	"data": null,
	"error": "doGetVMValue: sending request error",
	"code": "bad_request"
}
```

**Comment by tanghel** [comment]
Hello!

This issue was a temporary hiccup on the internal gateway

tested the above and it worked without issues.

These are endpoints that are proxied to the gateway.
You can find the documentation for them here: https://docs.elrond.com/sdk-and-tools/rest-api/virtual-machine

Will close this issue since it's not directly related to api.elrond.com

🙏
