### ISSUE TITLE
[Feature Request]: GET transactions withLogs=false and withOperations = true to remove log from operations

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#805]
### Describe the solution you'd like

It might be a stupid request, but...

When we make a request to https://api.elrond.com/transactions?withOperations=true&withLogs=false&withScamInfo=false , the logs are not available on the Transaction object, but could it be removed from Operations also?

![image](https://user-images.githubusercontent.com/26706013/189207667-ae5f1bed-04ad-44ef-8683-0dba0c636537.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

Operations are actually transaction logs interpreted in a more human-readable, unified way, without the need to perform base64 deserialization and interpretation. Every ESDT transfer, NFT mint / burn action, etc. exist both as log and as operation, with operation being a bit more structured and easy to parse by dapps.

The naming `log` is just naming coincident. Maybe a more accurate name would have been `message`, since it's a "log message" emitted by the smart contract.

If you need further clarifications, feel free to re-open this issue :)
